export type DeferredScreenState = 'deferred' | 'legacy-alias' | 'internal-tool';
export type DeferredScreenKey = 'marketing-funnels' | 'marketing-funnel-detail' | 'pages' | 'page-sections' | 'templates' | 'pages-seo' | 'quickstart' | 'event-logs' | 'qa-tools';
export interface ScreenMigrationState { key: DeferredScreenKey; view: string; state: DeferredScreenState; reason: string; userReachable: boolean; successors: readonly string[]; releaseTrigger: string; conditional?: 'marketing-funnel-detail'; }
export const DEFERRED_SCREEN_MIGRATION_STATES: readonly ScreenMigrationState[] = [
  { key: 'marketing-funnels', view: 'marketing-funnels', state: 'deferred', reason: 'Creation and editing remain legacy and are not production-mature.', userReachable: true, successors: [], releaseTrigger: 'A supported marketing-page product contract and dedicated migration.' },
  { key: 'marketing-funnel-detail', view: 'funnel-detail', conditional: 'marketing-funnel-detail', state: 'deferred', reason: 'Only marketing-mode detail retains the legacy funnel editor; Site Page Detail is permanent.', userReachable: true, successors: [], releaseTrigger: 'A supported marketing-page detail workflow and dedicated migration.' },
  { key: 'pages', view: 'pages', state: 'legacy-alias', reason: 'Legacy page table overlaps the permanent site-page and Builder workflows.', userReachable: true, successors: ['funnels', 'builder'], releaseTrigger: 'Route-retirement verification after legacy callers are removed.' },
  { key: 'page-sections', view: 'page-sections', state: 'deferred', reason: 'Raw section JSON editor is incomplete and superseded by Builder.', userReachable: true, successors: ['builder'], releaseTrigger: 'A product decision to retire or replace the raw editor.' },
  { key: 'templates', view: 'templates', state: 'deferred', reason: 'Legacy template management is not a mature production workflow.', userReachable: true, successors: ['builder'], releaseTrigger: 'A supported template-management contract and dedicated migration.' },
  { key: 'pages-seo', view: 'pages-seo', state: 'legacy-alias', reason: 'Legacy landing hub duplicates current website-management destinations.', userReachable: true, successors: ['funnels', 'seo-pages', 'website-structure', 'website-navigation'], releaseTrigger: 'Route-retirement verification after legacy callers are removed.' },
  { key: 'quickstart', view: 'quickstart', state: 'deferred', reason: 'Static checklist is a placeholder rather than a settled workflow.', userReachable: true, successors: [], releaseTrigger: 'A defined onboarding product contract or route retirement.' },
  { key: 'event-logs', view: 'event-logs', state: 'internal-tool', reason: 'Diagnostic event inspection is an internal operational surface.', userReachable: true, successors: [], releaseTrigger: 'Internal-tools ownership decision.' },
  { key: 'qa-tools', view: 'qa-tools', state: 'internal-tool', reason: 'Simulation controls are internal diagnostic tooling.', userReachable: true, successors: [], releaseTrigger: 'Internal-tools ownership decision.' }
];
export function validateScreenMigrationStates(entries = DEFERRED_SCREEN_MIGRATION_STATES): void { const keys = new Set<string>(); for (const entry of entries) { if (keys.has(entry.key)) throw new Error(`Duplicate migration state: ${entry.key}`); keys.add(entry.key); if (!entry.reason || !entry.releaseTrigger) throw new Error(`Missing migration rationale: ${entry.key}`); if (entry.state === 'legacy-alias' && entry.successors.length === 0) throw new Error(`Alias successor required: ${entry.key}`); } }
