import { escapeHtmlText } from '../../crm_html_output';
import type { Website, WebsiteSettings } from '../../types';
import { renderButton, renderCard, renderField, renderInput, renderSelect } from '../primitives';

export interface WebsiteSettingsRendererInput { settings: WebsiteSettings; websites: readonly Website[]; activeWebsiteId: string | null; }

function safePreviewUrl(value: string): string | null {
  const candidate = value.trim();
  if (/^https?:\/\/[^\s"'<>]+$/i.test(candidate)) return candidate;
  if (/^data:image\/(?:png|jpe?g|gif|webp);base64,[a-z0-9+/=]+$/i.test(candidate)) return candidate;
  return null;
}

function colorControl(value: string): string {
  const safe = /^#[0-9a-f]{6}$/i.test(value) ? value : '#4f46e5';
  return `<input id="settings-primary-color-input" class="wo-input wo-website-settings-color-input" type="color" value="${escapeHtmlText(safe)}" aria-describedby="settings-primary-color-input-helper" onchange="window.updateSettingsField('primary_color', this.value)" oninput="window.updateSettingsField('primary_color', this.value)" />`;
}

export function renderWebsiteSettingsContent(input: WebsiteSettingsRendererInput): string {
  const { settings } = input;
  const logoUrl = safePreviewUrl(settings.logo_url || '');
  const switcher = input.websites.length > 1 ? renderField({ id: 'settings-website-select', label: 'Active website', controlHtml: renderSelect({ id: 'settings-website-select', options: input.websites.map(site => ({ value: site.id, label: `${site.name}${site.domain ? ` — ${site.domain}` : ''}`, selected: site.id === input.activeWebsiteId })), attributes: { onchange: 'window.selectWebsiteForSettings(this.value)' } }) }) : '';
  const profile = renderCard({ className: 'wo-website-settings-card', headerHtml: '<div><span class="wo-website-settings-eyebrow">Business details</span><h2>Business Profile</h2><p>Keep the contact details customers see on your website.</p></div>', bodyHtml: `<div class="wo-website-settings-fields wo-website-settings-fields--profile">${renderField({ id: 'settings-business-name-input', label: 'Business Name', required: true, controlHtml: renderInput({ id: 'settings-business-name-input', name: 'business_name', value: settings.business_name, required: true, attributes: { 'data-settings-field': 'business_name', onchange: "window.updateSettingsField('business_name', this.value)" } }) })}${renderField({ id: 'settings-phone-input', label: 'Public Phone', controlHtml: renderInput({ id: 'settings-phone-input', name: 'phone', type: 'tel', value: settings.phone, attributes: { onchange: "window.updateSettingsField('phone', this.value)" } }) })}${renderField({ id: 'settings-sms-number-input', label: 'Text/SMS Number', helperText: 'Leave blank to use the public phone number.', controlHtml: renderInput({ id: 'settings-sms-number-input', name: 'sms_number', type: 'tel', value: settings.sms_number || '', placeholder: settings.phone, attributes: { onchange: "window.updateSettingsField('sms_number', this.value)" } }) })}${renderField({ id: 'settings-email-input', label: 'Public Email', controlHtml: renderInput({ id: 'settings-email-input', name: 'email', type: 'email', value: settings.email, attributes: { onchange: "window.updateSettingsField('email', this.value)" } }) })}</div>` });
  const branding = renderCard({ className: 'wo-website-settings-card', headerHtml: '<div><span class="wo-website-settings-eyebrow">Visual identity</span><h2>Branding</h2><p>Preview the website brand assets stored for this site.</p></div>', bodyHtml: `<div class="wo-website-settings-fields wo-website-settings-fields--branding">${renderField({ id: 'settings-primary-color-input', label: 'Brand Color', helperText: `Current value: ${settings.primary_color || '#4f46e5'}`, controlHtml: `<div class="wo-website-settings-color-control">${colorControl(settings.primary_color || '')}<code id="settings-primary-color-display">${escapeHtmlText(settings.primary_color || '#4f46e5')}</code></div>` })}${renderField({ id: 'settings-logo-url-input', label: 'Logo URL', controlHtml: `<div class="wo-website-settings-logo-field">${renderInput({ id: 'settings-logo-url-input', name: 'logo_url', type: 'url', value: settings.logo_url || '', attributes: { onchange: "window.updateSettingsField('logo_url', this.value)" } })}${logoUrl ? `<img id="settings-logo-img" class="wo-website-settings-logo-preview" src="${escapeHtmlText(logoUrl)}" alt="Business logo preview" />` : '<span class="wo-website-settings-logo-unavailable" role="status">Preview unavailable</span>'}</div>` })}</div>` });
  const tracking = renderCard({ className: 'wo-website-settings-card', headerHtml: '<div><span class="wo-website-settings-eyebrow">Measurement</span><h2>Tracking &amp; Marketing</h2><p>Connect the tracking tools currently supported by Website Settings.</p></div>', bodyHtml: `<div class="wo-website-settings-fields wo-website-settings-fields--tracking">${renderField({ id: 'settings-facebook-pixel-input', label: 'Facebook Pixel ID', controlHtml: renderInput({ id: 'settings-facebook-pixel-input', name: 'facebook_pixel_id', value: settings.facebook_pixel_id || '', placeholder: 'e.g. 1234567890', attributes: { 'data-settings-field': 'facebook_pixel_id', onchange: "window.updateSettingsField('facebook_pixel_id', this.value)" } }) })}${renderField({ id: 'settings-gtm-input', label: 'GTM Container ID', controlHtml: renderInput({ id: 'settings-gtm-input', name: 'gtm_id', value: settings.gtm_id || '', placeholder: 'e.g. GTM-XXXXXX', attributes: { 'data-settings-field': 'gtm_id', onchange: "window.updateSettingsField('gtm_id', this.value)" } }) })}</div>` });
  return `<section class="wo-website-settings" aria-label="Website Settings">${switcher}${profile}${branding}${tracking}</section>`;
}

export function renderWebsiteSettingsSaveAction(): string { return renderButton({ label: 'Save Settings', variant: 'primary', id: 'website-settings-save', attributes: { onclick: 'window.saveGlobalSettings()' } }); }
