import { escapeHtmlText } from '../../crm_html_output';
import type { NavigationTargetKind, ResolvedNavigationItem } from '../../builder_site_navigation_domain';
import { renderButton, renderCard, renderEmptyState, renderErrorState, renderField, renderInput, renderSelect, renderStatusBadge } from '../primitives';

export type WebsiteNavigationAuthority = 'legacy' | 'live' | 'draft' | 'conflict' | 'loading' | 'error';
export interface NavigationDestination { value: string; label: string; }
export interface NavigationEditorModel { isOpen: boolean; mode: 'add' | 'edit' | 'resolve_legacy'; label: string; targetKind: NavigationTargetKind; targetValue: string; visible: boolean; isCta: boolean; isSaving: boolean; errorMessage: string | null; destinations: NavigationDestination[]; }
export interface LegacyAdoptionCandidate { id: string; label: string; originalTarget: string; status: 'ready' | 'needs_attention'; reason?: string; }
export interface LegacyAdoptionReviewModel { isOpen: boolean; candidates: LegacyAdoptionCandidate[]; errorMessage: string | null; isSubmitting: boolean; }
export interface WebsiteNavigationModel { websiteName: string; authority: WebsiteNavigationAuthority; items: ResolvedNavigationItem[]; legacyItems: Array<{ label: string; path: string; visible: boolean }>; error?: string; editor?: NavigationEditorModel; adoptionReview?: LegacyAdoptionReviewModel; }
export interface WebsiteNavigationActions { add: string; edit: (id: string) => string; remove: (id: string) => string; move: (id: string, direction: 'up' | 'down') => string; toggle: (id: string) => string; adopt: string; discard: string; reload: string; }

const editorField = (field: string, value: string) => `window.setWebsiteNavigationEditorField('${field}', ${value})`;

function renderEditor(editor: NavigationEditorModel | undefined): string {
  if (!editor?.isOpen) return '';
  const target = editor.targetKind;
  const targetControl = target === 'homepage'
    ? '<p class="wo-website-navigation-editor-note">Points dynamically to this website’s homepage.</p>'
    : target === 'internal'
      ? renderField({ id: 'website-navigation-target', label: 'Destination', required: true, controlHtml: renderSelect({ id: 'website-navigation-target', required: true, options: [{ value: '', label: 'Select a site page', selected: !editor.targetValue }, ...editor.destinations.map(destination => ({ ...destination, selected: destination.value === editor.targetValue }))], attributes: { onchange: editorField('targetValue', 'this.value') } }) })
      : renderField({ id: 'website-navigation-target', label: target === 'external' ? 'External URL' : target === 'phone' ? 'Phone number' : 'Email address', required: true, controlHtml: renderInput({ id: 'website-navigation-target', type: target === 'external' ? 'url' : target === 'phone' ? 'tel' : 'email', value: editor.targetValue, placeholder: target === 'external' ? 'https://example.com' : target === 'phone' ? '+1 555 234 5678' : 'contact@example.com', attributes: { oninput: editorField('targetValue', 'this.value') } }) });
  return `<div class="wo-website-navigation-dialog-backdrop" role="presentation"><section class="wo-website-navigation-dialog" role="dialog" aria-modal="true" aria-labelledby="website-navigation-editor-title"><div class="wo-website-navigation-dialog-header"><h2 id="website-navigation-editor-title">${editor.mode === 'add' ? 'Add menu item' : editor.mode === 'resolve_legacy' ? 'Resolve legacy destination' : 'Edit menu item'}</h2>${renderButton({ label: 'Close', ariaLabel: 'Close editor', variant: 'ghost', icon: '×', iconOnly: true, attributes: { onclick: 'window.closeWebsiteNavigationEditor()' }, disabled: editor.isSaving })}</div><form class="wo-website-navigation-editor" onsubmit="event.preventDefault(); window.saveWebsiteNavigationEditor();">${editor.errorMessage ? `<div class="wo-website-navigation-error" role="alert">${escapeHtmlText(editor.errorMessage)}</div>` : ''}${renderField({ id: 'website-navigation-label', label: 'Menu label', required: true, controlHtml: renderInput({ id: 'website-navigation-label', value: editor.label, required: true, attributes: { oninput: editorField('label', 'this.value') } }) })}${renderField({ id: 'website-navigation-kind', label: 'Link type', controlHtml: renderSelect({ id: 'website-navigation-kind', options: [{ value: 'homepage', label: 'Homepage', selected: target === 'homepage' }, { value: 'internal', label: 'Site page', selected: target === 'internal' }, { value: 'external', label: 'External URL', selected: target === 'external' }, { value: 'phone', label: 'Phone number', selected: target === 'phone' }, { value: 'email', label: 'Email address', selected: target === 'email' }], attributes: { onchange: editorField('targetKind', 'this.value') } }) })}${targetControl}<div class="wo-website-navigation-editor-toggles"><label><input type="checkbox" ${editor.visible ? 'checked' : ''} onchange="${editorField('visible', 'this.checked')}"> Visible in menu</label><label><input type="checkbox" ${editor.isCta ? 'checked' : ''} onchange="${editorField('isCta', 'this.checked')}"> Display as CTA</label></div><div class="wo-website-navigation-dialog-actions">${renderButton({ label: 'Cancel', variant: 'secondary', attributes: { onclick: 'window.closeWebsiteNavigationEditor()' }, disabled: editor.isSaving })}${renderButton({ label: editor.isSaving ? 'Saving…' : editor.mode === 'add' ? 'Add item' : 'Save changes', variant: 'primary', type: 'submit', loading: editor.isSaving })}</div></form></section></div>`;
}

function renderAdoptionReview(review: LegacyAdoptionReviewModel | undefined): string {
  if (!review?.isOpen) return '';
  const unresolved = review.candidates.filter(candidate => candidate.status === 'needs_attention').length;
  const candidates = review.candidates.map(candidate => `<li class="wo-website-navigation-adoption-candidate"><div><strong>${escapeHtmlText(candidate.label)}</strong><span>${escapeHtmlText(candidate.originalTarget || '(no destination)')}</span>${candidate.reason ? `<small>${escapeHtmlText(candidate.reason)}</small>` : ''}</div><div class="wo-website-navigation-adoption-actions">${renderStatusBadge(candidate.status === 'ready' ? 'ready' : 'needs attention')}${renderButton({ label: candidate.status === 'ready' ? 'Edit' : 'Choose destination', size: 'sm', variant: 'secondary', attributes: { 'data-candidate-id': candidate.id, onclick: 'window.resolveWebsiteNavigationCandidate(this.dataset.candidateId)' } })}${renderButton({ label: 'Remove', size: 'sm', variant: 'danger', attributes: { 'data-candidate-id': candidate.id, onclick: 'window.removeWebsiteNavigationCandidate(this.dataset.candidateId)' } })}</div></li>`).join('');
  return `<div class="wo-website-navigation-dialog-backdrop" role="presentation"><section class="wo-website-navigation-dialog wo-website-navigation-adoption" role="dialog" aria-modal="true" aria-labelledby="website-navigation-adoption-title"><div class="wo-website-navigation-dialog-header"><h2 id="website-navigation-adoption-title">Review legacy conversion</h2>${renderButton({ label: 'Close', ariaLabel: 'Close conversion review', variant: 'ghost', icon: '×', iconOnly: true, attributes: { onclick: 'window.cancelWebsiteNavigationAdoption()' }, disabled: review.isSubmitting })}</div><p>Review every legacy link before creating an editable draft. Your public navigation will not change until Website Publish.</p>${review.errorMessage ? `<div class="wo-website-navigation-error" role="alert">${escapeHtmlText(review.errorMessage)}</div>` : ''}${unresolved ? `<div class="wo-website-navigation-attention" role="alert">${unresolved} item${unresolved === 1 ? '' : 's'} need attention before you can continue.</div>` : ''}<ol class="wo-website-navigation-adoption-list">${candidates || '<li>No legacy items found.</li>'}</ol><div class="wo-website-navigation-dialog-actions">${renderButton({ label: 'Cancel', variant: 'secondary', attributes: { onclick: 'window.cancelWebsiteNavigationAdoption()' }, disabled: review.isSubmitting })}${renderButton({ label: review.isSubmitting ? 'Creating draft…' : 'Create editable draft', variant: 'primary', attributes: { onclick: 'window.confirmWebsiteNavigationAdoption()' }, disabled: unresolved > 0 || review.isSubmitting, loading: review.isSubmitting })}</div></section></div>`;
}

export function renderWebsiteNavigationContent(model: WebsiteNavigationModel, actions: WebsiteNavigationActions): string {
  if (model.authority === 'loading') return `<section class="wo-website-navigation"><div class="wo-card" role="status" aria-busy="true"><div class="wo-card-body">Loading navigation…</div></div></section>`;
  if (model.authority === 'error' || model.authority === 'conflict') return `<section class="wo-website-navigation">${renderErrorState({ title: model.authority === 'conflict' ? 'Navigation conflict' : 'Navigation unavailable', message: model.error ?? 'Reload the latest navigation before making changes.', retryActionHtml: actions.reload })}</section>`;
  const authorityLabel = model.authority === 'legacy' ? 'Legacy navigation' : model.authority === 'draft' ? 'Unpublished changes' : 'Live';
  const error = model.error ? `<div class="wo-website-navigation-error" role="alert">${escapeHtmlText(model.error)}</div>` : '';
  const legacy = model.authority === 'legacy' ? `<div class="wo-website-navigation-legacy"><p>Legacy navigation remains authoritative until you explicitly convert it.</p>${model.legacyItems.length ? model.legacyItems.map(item => `<div class="wo-website-navigation-legacy-row"><strong>${escapeHtmlText(item.label)}</strong><code>${escapeHtmlText(item.path || '(no destination)')}</code>${renderStatusBadge(item.visible ? 'visible' : 'hidden')}</div>`).join('') : renderEmptyState({ title: 'No legacy menu items', description: 'The existing legacy menu is empty.' })}${renderButton({ label: 'Review conversion', variant: 'secondary', attributes: { onclick: actions.adopt } })}</div>` : '';
  const rows = model.items.map(item => `<li class="wo-website-navigation-item"><div class="wo-website-navigation-reorder">${actions.move(item.id, 'up')} ${actions.move(item.id, 'down')}</div><div class="wo-website-navigation-item-main"><strong>${escapeHtmlText(item.label)}</strong><span>${escapeHtmlText(item.resolution_details ?? item.resolved_href ?? item.target_value)}</span><small>${escapeHtmlText(item.target_kind)} · ${item.visible ? 'Visible' : 'Hidden'}${item.is_cta ? ' · CTA' : ''}</small>${item.resolution_status !== 'resolved' ? `<em>Needs attention: ${escapeHtmlText(item.resolution_details ?? item.resolution_status)}</em>` : ''}</div><div class="wo-website-navigation-actions">${actions.toggle(item.id)}${actions.edit(item.id)}${actions.remove(item.id)}</div></li>`).join('');
  const body = rows ? `<ol class="wo-website-navigation-list">${rows}</ol>` : renderEmptyState({ title: 'No menu items yet', description: 'Add a primary navigation item to begin.' });
  return `<section class="wo-website-navigation" aria-label="Website Navigation"><div class="wo-website-navigation-status"><span>Authority</span>${renderStatusBadge(authorityLabel)}${model.authority === 'draft' ? actions.discard : ''}</div>${error}${legacy}${model.authority !== 'legacy' ? `${renderCard({ className: 'wo-website-navigation-card', bodyHtml: `${body}<div class="wo-website-navigation-add">${actions.add}</div>` })}` : ''}${renderEditor(model.editor)}${renderAdoptionReview(model.adoptionReview)}</section>`;
}
