import { escapeHtmlText } from '../../crm_html_output';
import type { ResolvedNavigationItem, SiteNavigationItem } from '../../builder_site_navigation_domain';
import { renderCard, renderEmptyState, renderErrorState, renderStatusBadge } from '../primitives';

export type WebsiteNavigationAuthority = 'legacy' | 'live' | 'draft' | 'conflict' | 'loading' | 'error';
export interface WebsiteNavigationModel { websiteName: string; authority: WebsiteNavigationAuthority; items: ResolvedNavigationItem[]; legacyItems: Array<{ label: string; path: string; visible: boolean }>; error?: string; }
export interface WebsiteNavigationActions { add: string; edit: (id: string) => string; remove: (id: string) => string; move: (id: string, direction: 'up' | 'down') => string; toggle: (id: string) => string; adopt: string; revert: string; }

export function renderWebsiteNavigationContent(model: WebsiteNavigationModel, actions: WebsiteNavigationActions): string {
  if (model.authority === 'loading') return `<section class="wo-website-navigation"><div class="wo-card" role="status" aria-busy="true"><div class="wo-card-body">Loading navigation…</div></div></section>`;
  if (model.authority === 'error' || model.authority === 'conflict') return `<section class="wo-website-navigation">${renderErrorState({ title: model.authority === 'conflict' ? 'Navigation conflict' : 'Navigation unavailable', message: model.error ?? 'Reload the latest navigation before making changes.', retryActionHtml: actions.revert })}</section>`;
  const authorityLabel = model.authority === 'legacy' ? 'Legacy navigation' : model.authority === 'draft' ? 'Unpublished changes' : 'Live';
  const legacy = model.authority === 'legacy' ? `<div class="wo-website-navigation-legacy"><p>Legacy navigation remains authoritative until you explicitly convert it.</p>${model.legacyItems.length ? model.legacyItems.map(item => `<div class="wo-website-navigation-legacy-row"><strong>${escapeHtmlText(item.label)}</strong><code>${escapeHtmlText(item.path || '(no destination)')}</code>${renderStatusBadge(item.visible ? 'visible' : 'hidden')}</div>`).join('') : renderEmptyState({ title: 'No legacy menu items', description: 'The existing legacy menu is empty.' })}<button type="button" class="wo-button wo-button--secondary" ${actions.adopt ? '' : 'disabled'} onclick="${actions.adopt}">Review conversion</button></div>` : '';
  const rows = model.items.map((item, index) => `<li class="wo-website-navigation-item"><div class="wo-website-navigation-reorder">${actions.move(item.id, 'up')} ${actions.move(item.id, 'down')}</div><div class="wo-website-navigation-item-main"><strong>${escapeHtmlText(item.label)}</strong><span>${escapeHtmlText(item.resolution_details ?? item.resolved_href ?? item.target_value)}</span><small>${escapeHtmlText(item.target_kind)} · ${item.visible ? 'Visible' : 'Hidden'}${item.is_cta ? ' · CTA' : ''}</small>${item.resolution_status !== 'resolved' ? `<em>Needs attention: ${escapeHtmlText(item.resolution_details ?? item.resolution_status)}</em>` : ''}</div><div class="wo-website-navigation-actions">${actions.toggle(item.id)}${actions.edit(item.id)}${actions.remove(item.id)}</div></li>`).join('');
  const body = rows ? `<ol class="wo-website-navigation-list">${rows}</ol>` : renderEmptyState({ title: 'No menu items yet', description: 'Add a primary navigation item to begin.' });
  return `<section class="wo-website-navigation" aria-label="Website Navigation"><div class="wo-website-navigation-status"><span>Authority</span>${renderStatusBadge(authorityLabel)}${model.authority === 'draft' ? actions.revert : ''}</div>${legacy}${model.authority !== 'legacy' ? `${renderCard({ className: 'wo-website-navigation-card', bodyHtml: `${body}<div class="wo-website-navigation-add">${actions.add}</div>` })}` : ''}</section>`;
}
