import { describe, expect, it } from 'vitest';
import { PDF_MIME_TYPE, PDF_TEMPLATE_KEY, PDF_TEMPLATE_VERSION, renderIssuedInvoicePdf, sha256 } from './issued_invoice_pdf';
const spec = { issuer: { business_name: 'Café Wash', email: 'hello@example.test', phone: '555-0100' }, invoice: { invoice_number: 'INV-001', issued_at: '2026-09-01', due_at: '2026-09-15', customer_name: 'José García', customer_email: 'jose@example.test', customer_phone: '555', billing_address: '10 Montréal Way', currency: 'CAD', total_amount: '12.50' }, items: [{ order_index: 1, service_name: '<script>alert(1)</script>', description: 'Élite wash', quantity: '1', unit_price: '12.50', line_total: '12.50' }] };
describe('issued invoice PDF renderer', () => {
  it('creates deterministic bounded PDF bytes from ordered frozen specification data with Unicode text', async () => { const first = await renderIssuedInvoicePdf(spec); const second = await renderIssuedInvoicePdf(spec); expect(PDF_MIME_TYPE).toBe('application/pdf'); expect(Buffer.from(first).subarray(0, 5).toString()).toBe('%PDF-'); expect(first.byteLength).toBeGreaterThan(1000); expect(first.byteLength).toBeLessThan(6_291_456); expect(sha256(first)).toMatch(/^[0-9a-f]{64}$/); expect(Buffer.compare(Buffer.from(first), Buffer.from(second))).toBe(0); });
  it('ignores acceptance signature evidence outside the frozen document contract', async () => { const clean = await renderIssuedInvoicePdf(spec); const tainted = await renderIssuedInvoicePdf({ ...spec, acceptance_signature: 'must-not-render' } as typeof spec); expect(Buffer.compare(Buffer.from(clean), Buffer.from(tainted))).toBe(0); });
  it('fails closed for overlong text and unsupported glyphs', async () => { await expect(renderIssuedInvoicePdf({ ...spec, issuer: { ...spec.issuer, business_name: 'x'.repeat(501) } })).rejects.toThrow('PDF_TEXT_TOO_LONG'); await expect(renderIssuedInvoicePdf({ ...spec, issuer: { ...spec.issuer, business_name: 'WashOps 🧪' } })).rejects.toThrow(); });
  it('pins the DOC-1B1 template contract', () => expect([PDF_TEMPLATE_KEY, PDF_TEMPLATE_VERSION]).toEqual(['washops-issued-invoice', 1]));
});
