import { escapeHtmlText } from '../../crm_html_output';
import { renderBadge, renderCard, renderEmptyState, renderErrorState } from '../primitives';
import type { ReportsViewModel, Distribution } from './reports_model';

const currency = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const heading = (title: string, description: string, badge: string) => `<div class="wo-reports-heading"><div><h2>${escapeHtmlText(title)}</h2><p>${escapeHtmlText(description)}</p></div>${badge}</div>`;
const distribution = (rows: Distribution[], valueLabel: (row: Distribution) => string) => `<ul class="wo-reports-list">${rows.map(row => `<li><div class="wo-reports-row-label"><span>${escapeHtmlText(row.label)}</span><span>${row.count} · ${escapeHtmlText(valueLabel(row))}</span></div><div class="wo-reports-bar" role="img" aria-label="${escapeHtmlText(`${row.label}: ${row.count}, ${valueLabel(row)}`)}"><span style="width:${Math.max(0, Math.min(100, row.percentage))}%"></span></div></li>`).join('')}</ul>`;

export function renderReportsContent(model: ReportsViewModel): string {
  const leadsBody = !model.leadSources.available ? renderErrorState({ title: 'Lead source data unavailable', message: 'Contact data could not be loaded. Retry before relying on lead-source analytics.' }) : model.leadSources.total === 0 ? renderEmptyState({ title: 'No leads yet', description: 'Lead sources will be summarized when lead contacts are available.' }) : distribution(model.leadSources.rows, row => `${row.percentage.toFixed(0)}%`);
  const pipelineBody = !model.pipeline.available ? renderErrorState({ title: 'Pipeline data unavailable', message: 'Opportunity data could not be loaded. Retry before relying on pipeline analytics.' }) : model.pipeline.total === 0 ? renderEmptyState({ title: 'No open opportunities yet', description: 'Open opportunities will appear here by pipeline stage.' }) : `<div class="wo-reports-total"><span>Estimated pipeline value</span><strong>${escapeHtmlText(currency(model.pipeline.value))}</strong></div>${distribution(model.pipeline.rows, row => currency(row.value))}`;
  const quotesBody = !model.quotes.available ? renderErrorState({ title: 'Quote data unavailable', message: 'Quote data could not be loaded. Retry before relying on quote analytics.' }) : model.quotes.total === 0 ? renderEmptyState({ title: 'No quotes yet', description: 'Draft, sent, approved, and rejected quotes will appear here.' }) : `<div class="wo-reports-total"><span>Quoted value</span><strong>${escapeHtmlText(currency(model.quotes.quotedValue))}</strong><small>Quoted value is not earned revenue.</small></div><ul class="wo-reports-statuses">${model.quotes.statuses.map(item => `<li>${renderBadge({ label: item.label, variant: 'neutral' })}<strong>${item.count}</strong></li>`).join('')}</ul>`;
  return `<section class="wo-reports" aria-label="CRM reports"><div class="wo-reports-grid">${renderCard({ className: 'wo-reports-card', headerHtml: heading('Lead Sources', 'Owned lead contacts grouped by source.', model.leadSources.available ? renderBadge({ label: `${model.leadSources.total} leads`, variant: 'info' }) : renderBadge({ label: 'Unavailable', variant: 'danger' })), bodyHtml: leadsBody })}${renderCard({ className: 'wo-reports-card', headerHtml: heading('Open Pipeline', 'Open opportunities and estimated pipeline value by stage.', model.pipeline.available ? renderBadge({ label: `${model.pipeline.total} open`, variant: 'info' }) : renderBadge({ label: 'Unavailable', variant: 'danger' })), bodyHtml: pipelineBody })}${renderCard({ className: 'wo-reports-card', headerHtml: heading('Quote Workflow', 'Current owned quote workflow, separate from revenue.', model.quotes.available ? renderBadge({ label: `${model.quotes.total} total`, variant: 'neutral' }) : renderBadge({ label: 'Unavailable', variant: 'danger' })), bodyHtml: quotesBody })}</div></section>`;
}
