import { spawn } from 'node:child_process';
import { mkdirSync, rmSync } from 'node:fs';
import { chromium } from 'playwright';
const port = 5182, base = `http://127.0.0.1:${port}`, output = 'scratch/screenshots/phase1c_task7c5b';
const sizes = [['1440x900', 1440, 900], ['768x1024', 768, 1024], ['390x844', 390, 844]] as const;
const assert = (value: unknown, message: string): asserts value => { if (!value) throw new Error(message); };
async function ready() { for (let i = 0; i < 30; i += 1) { try { if ((await fetch(base)).ok) return; } catch {} await new Promise(resolve => setTimeout(resolve, 500)); } throw new Error('Vite unavailable'); }
async function ordinary(page: any, mobile: boolean, label: string) { const state = await page.evaluate(() => ({ shell: document.querySelectorAll('.wo-shell').length, main: document.querySelectorAll('main').length, sidebar: document.querySelectorAll('.sidebar').length, overflow: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) <= document.documentElement.clientWidth, drawer: getComputedStyle(document.querySelector<HTMLElement>('[data-shell-drawer-toggle]')!).display !== 'none' })); assert(state.shell === 1 && state.main === 1 && state.sidebar === 0 && state.overflow && state.drawer === mobile, `${label}: ${JSON.stringify(state)}`); }
async function run() { rmSync(output, { recursive: true, force: true }); mkdirSync(output, { recursive: true }); const vite = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(port)], { env: { ...process.env, VITE_ENABLE_BROWSER_FIXTURES: 'true', VITE_BUILDER_PUBLICATION_PERSISTENCE: 'local', VITE_BUILDER_MEDIA_PERSISTENCE: 'local' }, stdio: 'ignore' }); try { await ready(); const browser = await chromium.launch({ channel: 'chrome' }); try { for (const [name, width, height] of sizes) { const page = await browser.newPage({ viewport: { width, height } }); await page.addInitScript(() => localStorage.setItem('onboarding_seen', 'true')); await page.goto(`${base}/#/reports`); await page.waitForSelector('.wo-reports'); await ordinary(page, width < 1024, `Reports ${name}`); const text = await page.locator('.wo-reports').innerText(); assert(text.includes('Lead Sources') && text.includes('Open Pipeline') && text.includes('Quote Workflow') && !text.includes('Google Search'), 'Reports analytics state'); await page.screenshot({ path: `${output}/reports-${name}.png` }); for (const [route, selector] of [['/#/dashboard', '.wo-dashboard'], ['/#/clients', '.wo-contacts'], ['/#/opportunities', '.wo-opportunities'], ['/#/quotes', '.wo-quotes'], ['/#/invoices', '.wo-invoices']] as const) { await page.goto(`${base}${route}`); await page.waitForSelector(selector); await ordinary(page, width < 1024, route); } await page.goto(`${base}/#/builder?websiteId=ws-1&pageId=p3&action=edit`); await page.waitForSelector('.pb-canvas-area'); const builder = await page.evaluate(() => ({ shell: document.querySelectorAll('.wo-shell').length, main: document.querySelectorAll('main').length, sidebar: document.querySelectorAll('.sidebar').length, overflow: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) <= document.documentElement.clientWidth })); assert(builder.shell === 0 && builder.main === 1 && builder.sidebar === 0 && builder.overflow, `Builder ${name}`); await page.close(); } } finally { await browser.close(); } console.log('Task 7C.5B visual smoke PASS'); } finally { vite.kill(); } }
run().catch(error => { console.error(error); process.exit(1); });
