import { spawn } from 'node:child_process';
import { mkdirSync, rmSync } from 'node:fs';
import { chromium } from 'playwright';

const port = 5192; const base = `http://127.0.0.1:${port}`; const output = 'scratch/screenshots/phase1c_task7c6c2';
const assert = (value: unknown, message: string): asserts value => { if (!value) throw new Error(message); };
async function ready() { for (let i = 0; i < 30; i++) { try { if ((await fetch(base)).ok) return; } catch {} await new Promise(resolve => setTimeout(resolve, 400)); } throw new Error('Vite unavailable'); }
async function shell(page: any, label: string) { const state = await page.evaluate(() => ({ shell: document.querySelectorAll('.wo-shell').length, main: document.querySelectorAll('main').length, h1: document.querySelectorAll('h1').length, legacy: document.querySelectorAll('.sidebar').length, overflow: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) <= document.documentElement.clientWidth })); assert(state.shell === 1 && state.main === 1 && state.h1 === 1 && state.legacy === 0 && state.overflow, `${label}: ${JSON.stringify(state)}`); }
async function structure(page: any, name: string) { await page.goto(`${base}/#/website-dashboard?websiteId=ws-1`); await page.waitForSelector('.wo-website-dashboard'); await page.evaluate(async () => { const db = await import('/src/db.ts'); const user = String((window as any).currentUser || db.mockWebsites[0].user_id); db.mockWebsites.forEach(w => w.user_id = user); if (!db.mockWebsites.some(w => w.id === 'ws-2')) db.mockWebsites.push({ ...db.mockWebsites[0], id: 'ws-2', user_id: user, name: 'Site B', domain: 'b.example', homepage_funnel_id: 'fnl-2' }); if (!db.mockWebsiteRoutes.some(r => r.id === 'route-b')) db.mockWebsiteRoutes.push({ ...db.mockWebsiteRoutes[0], id: 'route-b', website_id: 'ws-2', funnel_id: 'fnl-2', path: '/site-b-only' }); }); await page.evaluate(() => (window as any).navigateTo('website-structure', undefined, { websiteManagementRoute: { status: 'valid', websiteId: 'ws-1' } })); await page.waitForSelector('.wo-website-structure'); await shell(page, name); const text = await page.locator('.wo-website-structure').innerText(); assert(text.includes('Mapped routes') && !text.includes('site-b-only'), `${name}: selected-site routes leaked`); await page.screenshot({ path: `${output}/structure-${name}.png` }); }
async function regressions(page: any) { for (const [route, selector] of [['website-dashboard?websiteId=ws-1','.wo-website-dashboard'], ['funnels?websiteId=ws-1','.wo-site-pages'], ['website-navigation?websiteId=ws-1','.wo-website-navigation'], ['reports','.wo-reports']] as const) { await page.goto(`${base}/#/${route}`); await page.waitForSelector(selector); await shell(page, route); } await page.goto(`${base}/#/builder?websiteId=ws-1&pageId=p3&action=edit`); await page.waitForSelector('.pb-canvas-area'); assert(await page.locator('.wo-shell').count() === 0, 'Builder must remain shell-free'); }
async function run() { rmSync(output, { recursive: true, force: true }); mkdirSync(output, { recursive: true }); const vite = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(port)], { env: { ...process.env, VITE_ENABLE_BROWSER_FIXTURES: 'true', VITE_BUILDER_PUBLICATION_PERSISTENCE: 'local', VITE_BUILDER_MEDIA_PERSISTENCE: 'local' }, stdio: 'ignore' }); try { await ready(); const browser = await chromium.launch({ channel: 'chrome' }); try { for (const [name,width,height] of [['1440x900',1440,900],['768x1024',768,1024],['390x844',390,844]] as const) { const page = await browser.newPage({ viewport: { width, height } }); await page.addInitScript(() => localStorage.setItem('onboarding_seen','true')); await structure(page,name); await regressions(page); await page.close(); } } finally { await browser.close(); } console.log('Task 7C.6C.2 visual smoke PASS'); } finally { vite.kill(); } }
run().catch(error => { console.error(error); process.exit(1); });
