import { spawn } from 'node:child_process';
import { mkdirSync, rmSync } from 'node:fs';
import { chromium } from 'playwright';
const port=5180,base=`http://127.0.0.1:${port}`,out='scratch/screenshots/phase1c_task7c4',sizes=[['1440x900',1440,900],['768x1024',768,1024],['390x844',390,844]] as const;
const assert=(value:unknown,message:string):asserts value=>{if(!value)throw new Error(message)};
async function ready(){for(let i=0;i<30;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(resolve=>setTimeout(resolve,500))}throw new Error('Vite unavailable')}
async function ordinary(page:any,mobile:boolean,label:string){const state=await page.evaluate(()=>{const drawer=document.querySelector<HTMLElement>('[data-shell-drawer-toggle]'),width=document.documentElement.clientWidth;return{shell:document.querySelectorAll('.wo-shell').length,main:document.querySelectorAll('main').length,legacy:document.querySelectorAll('.sidebar').length,overflow:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)<=width,drawer:drawer?getComputedStyle(drawer).display!=='none':false}});assert(state.shell===1&&state.main===1&&state.legacy===0&&state.overflow&&state.drawer===mobile,`${label}: ${JSON.stringify(state)}`)}
async function main(){rmSync(out,{recursive:true,force:true});mkdirSync(out,{recursive:true});const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(port)],{env:{...process.env,VITE_ENABLE_BROWSER_FIXTURES:'true',VITE_BUILDER_PUBLICATION_PERSISTENCE:'local',VITE_BUILDER_MEDIA_PERSISTENCE:'local'},stdio:'ignore'});try{await ready();const browser=await chromium.launch({channel:'chrome'});try{for(const [name,width,height] of sizes){const page=await browser.newPage({viewport:{width,height}});await page.addInitScript(()=>localStorage.setItem('onboarding_seen','true'));for(const [route,selector,shot] of [['/#/quotes','.wo-quotes','quotes'],['/#/new-quote','.wo-quote-composer','new-quote'],['/#/quote-preview/q1','.wo-quote-preview','quote-preview']] as const){await page.goto(`${base}${route}`);await page.waitForSelector(selector);await ordinary(page,width<1024,`${shot} ${name}`);await page.screenshot({path:`${out}/${shot}-${name}.png`})}for(const [route,selector] of [['/#/dashboard','.wo-dashboard'],['/#/clients','.wo-contacts'],['/#/opportunities','.wo-opportunities']] as const){await page.goto(`${base}${route}`);await page.waitForSelector(selector);await ordinary(page,width<1024,`${route} ${name}`)}await page.goto(`${base}/#/builder?websiteId=ws-1&pageId=p3&action=edit`);await page.waitForSelector('.pb-canvas-area');const builder=await page.evaluate(()=>({shell:document.querySelectorAll('.wo-shell').length,main:document.querySelectorAll('main').length,legacy:document.querySelectorAll('.sidebar').length,overflow:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)<=document.documentElement.clientWidth}));assert(builder.shell===0&&builder.main===1&&builder.legacy===0&&builder.overflow,JSON.stringify(builder));await page.close()}}finally{await browser.close()}console.log('Task 7C.4 visual smoke PASS')}finally{server.kill()}}
main().catch(error=>{console.error(error);process.exit(1)});
