import { spawn } from 'node:child_process';
import { mkdirSync, rmSync } from 'node:fs';
import { chromium } from 'playwright';
const port=5179, base=`http://127.0.0.1:${port}`, out='scratch/screenshots/phase1c_task7c3';
const sizes=[['1440x900',1440,900],['768x1024',768,1024],['390x844',390,844]] as const;
const assert=(v:unknown,m:string):asserts v=>{if(!v)throw new Error(m)};
async function ready(){for(let i=0;i<30;i++){try{if((await fetch(base)).ok)return}catch{} await new Promise(r=>setTimeout(r,500))}throw new Error('Vite unavailable')}
async function ordinary(page:any,mobile:boolean,label:string){const r=await page.evaluate(()=>{const drawer=document.querySelector<HTMLElement>('[data-shell-drawer-toggle]'), board=document.querySelector<HTMLElement>('.wo-pipeline-board'), viewport=document.documentElement.clientWidth;return{s:document.querySelectorAll('.wo-shell').length,m:document.querySelectorAll('main').length,side:document.querySelectorAll('.sidebar').length,over:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)<=viewport,drawer:drawer?getComputedStyle(drawer).display!=='none':false,board:board?{width:Math.round(board.getBoundingClientRect().width),right:Math.round(board.getBoundingClientRect().right),scrollWidth:board.scrollWidth,overflow:getComputedStyle(board).overflowX}:null,offenders:Array.from(document.querySelectorAll<HTMLElement>('body *')).filter(el=>el.getBoundingClientRect().right>viewport+1).slice(0,5).map(el=>({tag:el.tagName,className:el.className,right:Math.round(el.getBoundingClientRect().right)}))}});assert(r.s===1&&r.m===1&&r.side===0&&r.over&&r.drawer===mobile,`${label}: ${JSON.stringify(r)}`)}
async function main(){rmSync(out,{recursive:true,force:true});mkdirSync(out,{recursive:true});const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port',String(port)],{env:{...process.env,VITE_ENABLE_BROWSER_FIXTURES:'true',VITE_BUILDER_PUBLICATION_PERSISTENCE:'local',VITE_BUILDER_MEDIA_PERSISTENCE:'local'},stdio:'ignore'});try{await ready();const browser=await chromium.launch({channel:'chrome'});try{for(const [name,width,height] of sizes){const page=await browser.newPage({viewport:{width,height}});await page.addInitScript(()=>localStorage.setItem('onboarding_seen','true'));await page.goto(`${base}/#/opportunities`);await page.waitForSelector('.wo-pipeline-board');await ordinary(page,width<1024,`opportunities ${name}`);assert(await page.locator('.wo-pipeline-stage').count()>0,'stages missing');await page.screenshot({path:`${out}/opportunities-${name}.png`});for(const [route,sel] of [['/#/dashboard','.wo-dashboard'],['/#/clients','.wo-contacts'],['/#/contact-detail/c1','.wo-contact-detail']] as const){await page.goto(`${base}${route}`);await page.waitForSelector(sel);await ordinary(page,width<1024,`${route} ${name}`)}await page.goto(`${base}/#/builder?websiteId=ws-1&pageId=p3&action=edit`);await page.waitForSelector('.pb-canvas-area');const b=await page.evaluate(()=>({s:document.querySelectorAll('.wo-shell').length,m:document.querySelectorAll('main').length,side:document.querySelectorAll('.sidebar').length,over:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)<=document.documentElement.clientWidth}));assert(b.s===0&&b.m===1&&b.side===0&&b.over,JSON.stringify(b));await page.close()}}finally{await browser.close()}console.log('Task 7C.3 visual smoke PASS: 3 screenshots; Opportunities plus 12 regression route/viewport groups.')}finally{server.kill()}}
main().catch(e=>{console.error(e);process.exit(1)});
