import { spawn, execFileSync } from 'node:child_process';
import { mkdirSync, rmSync } from 'node:fs';
import { chromium } from 'playwright';

const port = 5195, base = `http://127.0.0.1:${port}`, output = 'scratch/screenshots/phase1c_task7c7';
const sizes = [['1440x900', 1440, 900], ['768x1024', 768, 1024], ['390x844', 390, 844]] as const;
const assert = (value: unknown, message: string): asserts value => { if (!value) throw new Error(message); };
async function ready() { for (let attempt = 0; attempt < 30; attempt += 1) { try { if ((await fetch(base)).ok) return; } catch {} await new Promise(resolve => setTimeout(resolve, 400)); } throw new Error('Vite unavailable'); }
async function shell(page: any, label: string) { const state = await page.evaluate(() => ({ shell: document.querySelectorAll('.wo-shell').length, main: document.querySelectorAll('main').length, h1: document.querySelectorAll('h1').length, legacy: document.querySelectorAll('.wo-lead-capture .form-group,.wo-lead-capture .btn-primary,.wo-lead-capture .lead-form-container').length, overflow: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) > document.documentElement.clientWidth })); assert(state.shell === 1 && state.main === 1 && state.h1 === 1 && state.legacy === 0 && !state.overflow, `${label}: ${JSON.stringify(state)}`); }
async function run() { rmSync(output, { recursive: true, force: true }); mkdirSync(output, { recursive: true }); let browser: any; const vite = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(port)], { env: { ...process.env, VITE_ENABLE_BROWSER_FIXTURES: 'true', VITE_BUILDER_PUBLICATION_PERSISTENCE: 'local', VITE_BUILDER_MEDIA_PERSISTENCE: 'local' }, stdio: 'ignore' }); try { await ready(); browser = await chromium.launch({ channel: 'chrome' }); for (const [name, width, height] of sizes) { const page = await browser.newPage({ viewport: { width, height } }); await page.addInitScript(() => localStorage.setItem('onboarding_seen', 'true')); await page.goto(`${base}/#/lead-capture`); await page.waitForSelector('.wo-lead-capture'); await shell(page, `Lead Capture ${name}`); for (const id of ['lead_name', 'lead_phone', 'lead_email', 'lead_address', 'lead_service_type', 'lead_message']) assert(await page.locator(`#${id}`).count() === 1, `${name}: missing ${id}`); assert(await page.getByRole('button', { name: 'Submit lead info' }).isVisible(), `${name}: submit unavailable`); await page.screenshot({ path: `${output}/lead-capture-${name}.png` }); for (const [route, selector] of [['dashboard', '.wo-dashboard'], ['clients', '.wo-contacts'], ['website-dashboard?websiteId=ws-1', '.wo-website-dashboard'], ['seo-pages?websiteId=ws-1', '.wo-local-seo']] as const) { await page.goto(`${base}/#/${route}`); await page.waitForSelector(selector); await shell(page, `${route} ${name}`); } await page.goto(`${base}/#/builder?websiteId=ws-1&pageId=p3&action=edit`); await page.waitForSelector('.pb-canvas-area'); const builder = await page.evaluate(() => ({ shell: document.querySelectorAll('.wo-shell').length, main: document.querySelectorAll('main').length, overflow: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth) > document.documentElement.clientWidth })); assert(builder.shell === 0 && builder.main === 1 && !builder.overflow, `Builder ${name}: ${JSON.stringify(builder)}`); await page.close(); } await browser.close(); browser = undefined; console.log('Task 7C.7 visual smoke PASS'); } finally { if (browser) await browser.close().catch(() => undefined); vite.kill(); if (process.platform === 'win32' && vite.pid) try { execFileSync('taskkill', ['/pid', String(vite.pid), '/t', '/f'], { stdio: 'ignore' }); } catch {} rmSync(output, { recursive: true, force: true }); } }
run().catch(error => { console.error(error); process.exitCode = 1; });
