import { describe, expect, it, vi } from 'vitest';
import { BuilderViewTransitionController } from './builder_view_transition';

describe('BuilderViewTransitionController', () => {
  it('renders directly without progressive enhancement', () => { const update = vi.fn(); new BuilderViewTransitionController().render({}, update); expect(update).toHaveBeenCalledOnce(); });
  it('starts one normal transition', async () => { const update = vi.fn(); const start = vi.fn((callback: () => void) => { callback(); return { finished: Promise.resolve() }; }); new BuilderViewTransitionController().render({ startViewTransition: start }, update); await Promise.resolve(); expect(start).toHaveBeenCalledOnce(); expect(update).toHaveBeenCalledOnce(); });
  it('renders rapid updates directly while a transition is active', () => { let finish: () => void = () => undefined; const pending = new Promise<void>(resolve => { finish = resolve; }); const start = vi.fn((callback: () => void) => { callback(); return { finished: pending }; }); const controller = new BuilderViewTransitionController(); const update = vi.fn(); controller.render({ startViewTransition: start }, update); controller.render({ startViewTransition: start }, update); expect(start).toHaveBeenCalledOnce(); expect(update).toHaveBeenCalledTimes(2); finish(); });
  it('falls back only for the expected skipped error at the origin', () => { const update = vi.fn(); const documentLike = { startViewTransition: () => { throw new DOMException('skip', 'AbortError'); } }; new BuilderViewTransitionController().render(documentLike, update); expect(update).toHaveBeenCalledOnce(); });
  it('absorbs an invalid-state abort reported by the browser after the update', async () => { const update = vi.fn(); const start = vi.fn((callback: () => void) => { callback(); return { finished: Promise.reject(new DOMException('Transition was aborted because of invalid state', 'InvalidStateError')) }; }); new BuilderViewTransitionController().render({ startViewTransition: start }, update); await Promise.resolve(); await Promise.resolve(); expect(start).toHaveBeenCalledOnce(); expect(update).toHaveBeenCalledOnce(); });
  it('does not swallow unexpected synchronous errors', () => { const error = new Error('unexpected'); const controller = new BuilderViewTransitionController(); expect(() => controller.render({ startViewTransition: () => { throw error; } }, vi.fn())).toThrow(error); });
});
