import { escapeHtmlText } from '../../crm_html_output';
import { formatContactPhone } from '../../crm_contact_phone';
import type { Contact, Opportunity, Quote, QuoteItem } from '../../types';
import { renderBadge, renderButton, renderCard, renderEmptyState, renderField, renderStatusBadge } from '../primitives';

type Tier = 'basic' | 'standard' | 'premium';
const tiers: Tier[] = ['basic', 'standard', 'premium'];
export interface QuoteDraftItem { service: string; description: string; quantity: number; price: number; tier: Tier; }
export interface QuotesModel { userId: string; quotes: Quote[]; contacts: Contact[]; editable: boolean; }
export interface NewQuoteModel { userId: string; contacts: Contact[]; opportunities: Opportunity[]; contactId: string; opportunityId: string; items: QuoteDraftItem[]; }
export interface QuotePreviewModel { userId: string; quoteId: string; quotes: Quote[]; contacts: Contact[]; items: QuoteItem[]; editable: boolean; }
const currency = (value: number) => `$${Number.isFinite(value) ? value.toLocaleString('en-US') : '0'}`;
const ownedContact = (contacts: Contact[], userId: string, id: string) => contacts.find(contact => contact.user_id === userId && contact.id === id);

export function ownedQuotes(model: QuotesModel): Quote[] { return model.quotes.filter(quote => quote.user_id === model.userId); }
export function renderQuotesContent(model: QuotesModel): string {
  const quotes = ownedQuotes(model);
  const rows = quotes.map(quote => {
    const contact = ownedContact(model.contacts, model.userId, quote.contact_id);
    const actions = `<div class="wo-quotes-actions"><button type="button" class="wo-button wo-button--secondary wo-button--sm" onclick="event.stopPropagation();window.navigateTo('quote-preview','${quote.id}')">Preview</button><button type="button" class="wo-button wo-button--ghost wo-button--sm" onclick="event.stopPropagation();window.navigateTo('contact-detail','${quote.contact_id}')">Contact</button>${model.editable && quote.status === 'draft' ? `<button type="button" class="wo-button wo-button--primary wo-button--sm" onclick="event.stopPropagation();window.sendQuote('${quote.id}')">Send</button>` : ''}${model.editable && quote.status === 'sent' ? `<button type="button" class="wo-button wo-button--primary wo-button--sm" onclick="event.stopPropagation();window.approveQuote('${quote.id}')">Approve</button><button type="button" class="wo-button wo-button--danger wo-button--sm" onclick="event.stopPropagation();window.rejectQuote('${quote.id}')">Reject</button>` : ''}</div>`;
    return `<tr class="wo-quotes-row" tabindex="0" role="link" onclick="window.navigateTo('quote-preview','${quote.id}')" onkeydown="if(event.target === event.currentTarget && (event.key === 'Enter'||event.key === ' ')){event.preventDefault();window.navigateTo('quote-preview','${quote.id}')}" data-quote-id="${escapeHtmlText(quote.id)}"><td data-label="Quote"><strong>Q-${escapeHtmlText(quote.id)}</strong>${quote.selected_tier ? `<span class="wo-quotes-tier">${escapeHtmlText(quote.selected_tier)} option</span>` : ''}</td><td data-label="Contact">${escapeHtmlText(contact?.name ?? 'Contact unavailable')}</td><td data-label="Status">${renderStatusBadge(`quote-${quote.status}`)}</td><td data-label="Quoted value"><strong>${escapeHtmlText(currency(quote.total_amount))}</strong></td><td data-label="Created">${escapeHtmlText(new Date(quote.created_at).toLocaleDateString())}</td><td data-label="Actions">${actions}</td></tr>`;
  }).join('');
  return `<div class="wo-quotes"><section class="wo-quotes-summary" aria-label="Quote summary"><span>${quotes.length} ${quotes.length === 1 ? 'quote' : 'quotes'}</span><span>${quotes.filter(quote => quote.status === 'sent').length} awaiting response</span><strong>${escapeHtmlText(currency(quotes.reduce((sum, quote) => sum + quote.total_amount, 0)))} quoted value</strong>${model.editable ? '' : renderBadge({ label: 'Status actions are read-only in production', variant: 'neutral' })}</section>${renderCard({ className: 'wo-quotes-list-card', bodyHtml: rows ? `<div class="wo-quotes-table-wrap"><table class="wo-quotes-table"><thead><tr><th>Quote</th><th>Contact</th><th>Status</th><th>Quoted value</th><th>Created</th><th><span class="wo-sr-only">Actions</span></th></tr></thead><tbody>${rows}</tbody></table></div>` : renderEmptyState({ title: 'No quotes yet', description: 'Create a quote when a customer is ready for service.' }) })}</div>`;
}

export function ownedNewQuoteContacts(model: NewQuoteModel): Contact[] { return model.contacts.filter(contact => contact.user_id === model.userId); }
export function ownedNewQuoteOpportunities(model: NewQuoteModel): Opportunity[] { return model.opportunities.filter(opportunity => opportunity.user_id === model.userId && opportunity.contact_id === model.contactId); }
function renderTierComposer(tier: Tier, items: QuoteDraftItem[]): string {
  const tierItems = items.map((item, index) => ({ ...item, index })).filter(item => item.tier === tier);
  const total = tierItems.reduce((sum, item) => sum + item.quantity * item.price, 0);
  const body = tierItems.map(item => `<div class="wo-quote-line-item"><div class="wo-quote-line-heading"><input class="wo-field-input" aria-label="${escapeHtmlText(tier)} service name" value="${escapeHtmlText(item.service)}" placeholder="Service name" onchange="window.updateLineItem(${item.index},'service',this.value)"><button type="button" class="wo-button wo-button--ghost wo-button--sm" aria-label="Remove item" onclick="window.removeLineItem(${item.index})">Remove</button></div><textarea class="wo-field-textarea" aria-label="${escapeHtmlText(tier)} description" placeholder="Description" rows="2" onchange="window.updateLineItem(${item.index},'description',this.value)">${escapeHtmlText(item.description)}</textarea><div class="wo-quote-line-values"><label>Qty<input class="wo-field-input" type="number" value="${escapeHtmlText(item.quantity)}" oninput="window.updateLineItem(${item.index},'quantity',this.value,true)"></label><label>Price<input class="wo-field-input" type="number" value="${escapeHtmlText(item.price)}" oninput="window.updateLineItem(${item.index},'price',this.value,true)"></label><strong id="line-total-${item.index}">${escapeHtmlText(currency(item.quantity * item.price))}</strong></div></div>`).join('') || `<p class="wo-quote-empty-tier">No items in this option.</p>`;
  return renderCard({ className: 'wo-quote-tier-composer', bodyHtml: `<div class="wo-quote-tier-heading"><h2>${escapeHtmlText(tier)} option</h2><button type="button" class="wo-button wo-button--secondary wo-button--sm" onclick="window.addLineItem('${tier}')">Add item</button></div>${body}<div class="wo-quote-tier-total"><span>Option total</span><strong id="tier-total-${tier}">${escapeHtmlText(currency(total))}</strong></div>` });
}
export function renderNewQuoteContent(model: NewQuoteModel): string {
  const contacts = ownedNewQuoteContacts(model); const opportunities = ownedNewQuoteOpportunities(model);
  const contactOptions = contacts.map(contact => `<option value="${escapeHtmlText(contact.id)}" ${model.contactId === contact.id ? 'selected' : ''}>${escapeHtmlText(contact.name)}</option>`).join('');
  const opportunityOptions = opportunities.map(opportunity => `<option value="${escapeHtmlText(opportunity.id)}" ${model.opportunityId === opportunity.id ? 'selected' : ''}>${escapeHtmlText(currency(opportunity.value))} — ${escapeHtmlText(opportunity.pipeline_stage)}</option>`).join('');
  const setup = renderCard({ className: 'wo-quote-composer-setup', bodyHtml: `<div class="wo-quote-form-grid">${renderField({ id: 'quote-contact', label: 'Select contact', required: true, controlHtml: `<select id="quote-contact" class="wo-field-select" onchange="window.updateNewQuoteContact(this.value)"><option value="">Choose contact</option>${contactOptions}</select>` })}${renderField({ id: 'quote-opportunity', label: 'Select opportunity', helperText: 'Optional; only opportunities for the selected contact are shown.', controlHtml: `<select id="quote-opportunity" class="wo-field-select" onchange="window.newQuoteOpportunityId=this.value"><option value="">No opportunity</option>${opportunityOptions}</select>` })}</div>` });
  return `<div class="wo-quote-composer">${setup}<section class="wo-quote-tier-grid" aria-label="Service level options">${tiers.map(tier => renderTierComposer(tier, model.items)).join('')}</section>${renderCard({ className: 'wo-quote-notes-card', bodyHtml: renderField({ id: 'quote-notes', label: 'Internal notes or terms', controlHtml: '<textarea id="quote-notes" class="wo-field-textarea" rows="4" placeholder="Terms or project details"></textarea>' }) })}</div>`;
}

export function getOwnedQuotePreview(model: QuotePreviewModel): { quote: Quote; contact?: Contact; items: QuoteItem[] } | undefined {
  const quote = model.quotes.find(candidate => candidate.user_id === model.userId && candidate.id === model.quoteId); if (!quote) return undefined;
  return { quote, contact: ownedContact(model.contacts, model.userId, quote.contact_id), items: model.items.filter(item => item.user_id === model.userId && item.quote_id === quote.id) };
}
export function renderQuotePreviewContent(model: QuotePreviewModel): string {
  const resolved = getOwnedQuotePreview(model); if (!resolved) return renderEmptyState({ title: 'Quote unavailable', description: 'This quote is unavailable for the current account.' });
  const { quote, contact, items } = resolved;
  const tierHtml = tiers.map(tier => { const tierItems = items.filter(item => item.tier === tier || (!item.tier && tier === 'basic')); const total = tierItems.reduce((sum, item) => sum + item.total, 0); const selected = quote.selected_tier === tier; return renderCard({ className: `wo-quote-preview-tier${selected ? ' wo-quote-preview-tier--selected' : ''}`, bodyHtml: `${selected ? renderBadge({ label: 'Selected option', variant: 'success' }) : ''}<h2>${escapeHtmlText(tier)} service level</h2><strong class="wo-quote-preview-total">${escapeHtmlText(currency(total))}</strong>${model.editable ? `<button type="button" class="wo-button ${selected ? 'wo-button--secondary' : 'wo-button--primary'} no-print" onclick="window.selectQuoteTier('${quote.id}','${tier}')">${selected ? 'Selected' : `Choose ${tier}`}</button>` : ''}<ul>${tierItems.map(item => `<li><strong>${escapeHtmlText(item.service_name)}</strong><span>${escapeHtmlText(item.description)}</span><em>${escapeHtmlText(currency(item.total))}</em></li>`).join('') || '<li class="wo-quote-empty-tier">No items included.</li>'}</ul>` }); }).join('');
  return `<article class="wo-quote-preview"><header class="wo-quote-preview-header"><div><p class="wo-quotes-tier">Quote Q-${escapeHtmlText(quote.id)}</p><h2>Service quote</h2><p>${renderStatusBadge(`quote-${quote.status}`)} <span>Quoted value ${escapeHtmlText(currency(quote.total_amount))}</span></p></div><div class="wo-quote-preview-contact"><strong>${escapeHtmlText(contact?.name ?? 'Contact unavailable')}</strong><span>${escapeHtmlText(contact?.address ?? '')}</span><span>${escapeHtmlText(contact?.email ?? '')}</span><span>${escapeHtmlText(contact ? formatContactPhone(contact.phone) : '')}</span></div></header><section class="wo-quote-preview-tiers" aria-label="Service levels">${tierHtml}</section>${quote.notes ? `<section class="wo-quote-preview-notes"><h2>Additional notes</h2><p>${escapeHtmlText(quote.notes)}</p></section>` : ''}${model.editable && quote.status === 'approved' ? `<div class="no-print"><button type="button" class="wo-button wo-button--primary" onclick="window.convertToInvoice('${quote.id}')">Convert to invoice</button></div>` : ''}${model.editable ? '' : `<p class="wo-quote-production-notice no-print">Quote option and status changes are unavailable in production.</p>`}</article>`;
}
